[2021-11-22 13:14:51,001] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: ELT-python-snowflake.datamodel_dimstatus manual__2021-11-22T13:13:31.092870+00:00 [queued]>
[2021-11-22 13:14:51,029] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: ELT-python-snowflake.datamodel_dimstatus manual__2021-11-22T13:13:31.092870+00:00 [queued]>
[2021-11-22 13:14:51,031] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-11-22 13:14:51,033] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2021-11-22 13:14:51,033] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-11-22 13:14:51,058] {taskinstance.py:1262} INFO - Executing <Task(BashOperator): datamodel_dimstatus> on 2021-11-22 13:13:31.092870+00:00
[2021-11-22 13:14:51,068] {standard_task_runner.py:52} INFO - Started process 1111 to run task
[2021-11-22 13:14:51,081] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ELT-python-snowflake', 'datamodel_dimstatus', 'manual__2021-11-22T13:13:31.092870+00:00', '--job-id', '64', '--raw', '--subdir', 'DAGS_FOLDER/ELT-python-snowflake.py', '--cfg-path', '/tmp/tmppuk8y9b1', '--error-file', '/tmp/tmp7ric6xiw']
[2021-11-22 13:14:51,083] {standard_task_runner.py:77} INFO - Job 64: Subtask datamodel_dimstatus
[2021-11-22 13:14:51,208] {logging_mixin.py:109} INFO - Running <TaskInstance: ELT-python-snowflake.datamodel_dimstatus manual__2021-11-22T13:13:31.092870+00:00 [running]> on host bd3f5d3b0fb3
[2021-11-22 13:14:51,319] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ELT-python-snowflake
AIRFLOW_CTX_TASK_ID=datamodel_dimstatus
AIRFLOW_CTX_EXECUTION_DATE=2021-11-22T13:13:31.092870+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-11-22T13:13:31.092870+00:00
[2021-11-22 13:14:51,321] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2021-11-22 13:14:51,324] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'python3 /opt/***/elt/user-orders/transform-snowflake/6_enrich_to_datamodel/extract_to_dimstatus.py']
[2021-11-22 13:14:51,345] {subprocess.py:85} INFO - Output:
[2021-11-22 13:14:56,993] {subprocess.py:89} INFO - WARNING: An illegal reflective access operation has occurred
[2021-11-22 13:14:57,000] {subprocess.py:89} INFO - WARNING: Illegal reflective access by org.apache.spark.unsafe.Platform (file:/home/***/.local/lib/python3.7/site-packages/pyspark/jars/spark-unsafe_2.12-3.1.1.jar) to constructor java.nio.DirectByteBuffer(long,int)
[2021-11-22 13:14:57,013] {subprocess.py:89} INFO - WARNING: Please consider reporting this to the maintainers of org.apache.spark.unsafe.Platform
[2021-11-22 13:14:57,014] {subprocess.py:89} INFO - WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
[2021-11-22 13:14:57,016] {subprocess.py:89} INFO - WARNING: All illegal access operations will be denied in a future release
[2021-11-22 13:14:58,274] {subprocess.py:89} INFO - 21/11/22 13:14:58 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2021-11-22 13:14:59,217] {subprocess.py:89} INFO - Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
[2021-11-22 13:14:59,222] {subprocess.py:89} INFO - Setting default log level to "WARN".
[2021-11-22 13:14:59,223] {subprocess.py:89} INFO - To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
[2021-11-22 13:15:01,996] {subprocess.py:89} INFO - 21/11/22 13:15:01 WARN Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.
[2021-11-22 13:15:31,348] {subprocess.py:89} INFO - /home/***/.local/lib/python3.7/site-packages/snowflake/connector/options.py:97: UserWarning: You have an incompatible version of 'pyarrow' installed (4.0.1), please install a version that adheres to: 'pyarrow<5.1.0,>=5.0.0; extra == "pandas"'
[2021-11-22 13:15:31,350] {subprocess.py:89} INFO -   _expected_pyarrow_version,
[2021-11-22 13:15:32,474] {subprocess.py:93} INFO - Command exited with return code 0
[2021-11-22 13:15:32,542] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=ELT-python-snowflake, task_id=datamodel_dimstatus, execution_date=20211122T131331, start_date=20211122T131451, end_date=20211122T131532
[2021-11-22 13:15:32,628] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-11-22 13:15:32,944] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
